name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  call-workflow:
    uses: wverastegui/demo-called-workflow-tokens/.github/workflows/add_issue_to_project.yml@main
    secrets: inherit
